# command: python main.py --config benchmark/2x3
# RunInfo:
run-id: BD-2x3-Benchmark # for identifying in logs and in folders etc
continue-run: false # continue training from previous run
notes: Benchmarking Other approaches on 2x3 layouts -- BD
tags: Paper-2x3 # comma separated list of tags for this run
# Environment:
# level_types = (open-divider, partial-divider, full-divider, cross-divider, block-divider, ring-divider)
level: open-divider_salad, partial-divider_salad, full-divider_salad, ring-divider_salad, open-divider_onion-salad, block-divider_onion-salad  # level file txt
num-agents: 2
num-orders: 3
max-num-timesteps: 150 # quit after this many timesteps
max-num-subtasks: 14
seed: 1
device: cuda
# Environment Switches
record: false
randomize: true
# Mode:
evaluate: true
# Agents:
model1: bd
model2: bd
num-processes: 10 # number of parallel environments / number of eval episodes
# HyperParameters - Bayesian Delegation:
#### Delegation Planner
beta: 1.3
#### Navigation Planner
alpha: 0.03
tau: 2
cap: 25
main-cap: 50