# command: python main.py --config benchmark/2x3
# RunInfo:
run-id: UP-2x3-Benchmark # for identifying in logs and in folders etc
continue-run: false # continue training from previous run
notes: Benchmarking Other approaches on 2x3 layouts -- UP
tags: eval-baseline-2, 2x3, benchmark-up # comma separated list of tags for this run
# Environment:
# level_types = (open-divider, partial-divider, full-divider, cross-divider, block-divider, ring-divider)
level: open-divider_salad, partial-divider_salad, full-divider_salad, block-divider_salad, ring-divider_salad, open-divider_onion-salad, block-divider_onion-salad  # level file txt
num-agents: 2
num-orders: 1
max-num-timesteps: 100 # quit after this many timesteps
max-num-subtasks: 14
seed: 1
device: cuda
# Environment Switches
record: false
randomize: true
# Mode:
evaluate: true
# Agents:
model1: up
model2: up
num-processes: 5 # number of parallel environments / number of eval episodes
# HyperParameters - Bayesian Delegation:
#### Delegation Planner
beta: 1.3
#### Navigation Planner
alpha: 0.03
tau: 2
cap: 50
main-cap: 75