# RunInfo:
run-id: # for identifying in logs and in folders etc
notes: # What makes this run special
tags: # comma separated list of tags for this run

# Environment:

level: open-divider_salad, partial-divider_salad, full-divider_salad, cross-divider_salad, block-divider_salad, ring-divider_salad
num-agents: 2 # upto 5
num-orders: 3 # upto 5
max-num-timesteps: 100 # quit after this many timesteps
max-num-subtasks: 14
seed: 1
device: cpu # or cuda
# Environment Switches
record: True
randomize: False

# Mode:
play: False
train: False
evaluate: False
sweep: False

# Agents:
# Model type for agent (mappo, seac, ppo, bd, up, dc, fb, or greedy) must match num-agents
model1: mappo
model2: ppo
model3: bd 
model4: greedy 
#Model files -- to load pretrained models (only works for rl and --evaluate mode)
#model1-path: # path to model file
#model2-path: 
#model3-path: 
#model4-path:

# Training Parameters:
num-processes: 1 # number of parallel environments
# MAPPO and PPO
num-total-timesteps: 1000000
num-steps-per-update: 100
# SEAC
num-episodes: 5000
num-timesteps-per-episode: 100 # Models update after every n steps

#- HyperParameters - MAPPO:
share-policy: true
use-centralized-v: true
hidden-size: 128
num-mlp-hidden-layers: 1
use-popart: false
use-valuenorm: false
use-featurenorm: true
use-naive-recurrent-policy: true
use-recurrent-policy: true
num-rnn-hidden-layers: 1
rnn-data-length: 10
lr: 0.0003
critic-lr: 0.0003
adam-eps: 0.00001
num-epoch: 10
clip-range: 0.2
batch-size: 1
entropy-coef: 0.01
value-loss-coef: 0.1
max-grad-norm: 0.5
use-gae: True
gamma: 0.99
gae-lambda: 0.95


# HyperParameters - PPO:
#batch-size: 32
#lr: 0.001
#gamma: 0.99
#gae-lambda: 0.95
#clip-range: 0.05
#entropy-coef: 0.1
#value-loss-coef: 0.1
#max-grad-norm: 0.5


# HyperParameters - SEAC (Shared Experience Actor Critic):
#lr: 0.0009
#adam-eps: 0.001
#use_gae: False
#gamma: 0.95
#gae-lambda: 0.95
#entropy-coef: 0.05
#value-loss_coef: 0.5
seac-coef: 1.0
#max-grad-norm: 0.5

# HyperParameters - Bayesian Delegation:
#### Delegation Planner
beta: 1.3
#### Navigation Planner
alpha: 0.02
tau: 2
cap: 50
main-cap: 75